package scanner;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 10 11:18:01 PDT 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int EOF = 0;
    public static final int ERR = 1;
    public static final int ID = 2;
    public static final int COLON = 3;
    public static final int BOOL_KW = 4;
    public static final int CHAR_KW = 5;
    public static final int INT_KW = 6;
    public static final int REAL_KW = 7;
    public static final int STRING_KW = 8;
    public static final int ARRAY = 9;
    public static final int OF = 10;
    public static final int COMMA = 11;
    public static final int ASSMNT = 12;
    public static final int LEFT_PAREN = 13;
    public static final int RT_PAREN = 14;
    public static final int LEFT_BRKT = 15;
    public static final int RT_BRKT = 16;
    public static final int FUNC = 17;
    public static final int PROCEDURE = 18;
    public static final int SEMI = 19;
    public static final int BEGIN = 20;
    public static final int END = 21;
    public static final int RETURN = 22;
    public static final int PLUS = 23;
    public static final int MINUS = 24;
    public static final int TIMES = 25;
    public static final int DIVIDE = 26;
    public static final int B_AND = 27;
    public static final int XOR = 28;
    public static final int B_OR = 29;
    public static final int L_OR = 30;
    public static final int L_AND = 31;
    public static final int MOD = 32;
    public static final int L_NOT = 33;
    public static final int WHILE = 34;
    public static final int DO = 35;
    public static final int IF = 36;
    public static final int THEN = 37;
    public static final int ELSE = 38;
    public static final int LESS = 39;
    public static final int GTR = 40;
    public static final int EQ = 41;
    public static final int NOT_EQ = 42;
    public static final int LESS_EQ = 43;
    public static final int GTR_EQ = 44;
    public static final int VAR = 45;
    public static final int PROGRAM = 46;
    public static final int DOT = 47;
    public static final int TYPE = 48;
    public static final int BOOL = 50;
    public static final int CHAR = 51;
    public static final int INT = 52;
    public static final int REAL = 53;
    public static final int STRING = 54;
    public static final int WRITE = 55;
    public static final int READ = 56;
}